# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: name-tests-test
    -   id: detect-private-key
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.11
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        files: ^project
        args: [--ignore-missing-imports]
        additional_dependencies: [types-PyYAML==6.0.12.12]
